baseURL: https://liyi.dev/
languageCode: en-us
title: Ice Tea DevOps
theme: PaperMod

minify:
  disableXML: true
  minifyOutput: true


params:
  contact:
    email: tranngocphat0901@gmail.com
    phone: +84392949809
  subtitle: Ice Tea DevOps - Giải Nhiệt Hệ Thống, Tối Ưu Triển Khai
  environment: production
  author: "Patrick Tran"
  ShowPostCover: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowToc: true
  ShowBreadCrumbs: true
  defaultTheme: auto  # dark/light mode
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: true
  homeInfoParams:
    Title: "Chào mừng đến với blog DevOps"
    Content: "Chia sẻ kiến thức về DevOps, Cloud, Terraform, Kubernetes..."

menu:
  main:
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
